In [2]:
import numpy as np

$
\begin{bmatrix} 
1 & 2 & 3 & 4
\end{bmatrix}
$

In [4]:
my_list = [1,2,3,4]

my_array = np.array(my_list)

print(my_array)
print(type(my_array))


[1 2 3 4]
<class 'numpy.ndarray'>


$
\begin{bmatrix} 
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8
\end{bmatrix}
$

In [5]:
second_list = [5,6,7,8]

two_d_array = np.array([my_list , second_list])
print(two_d_array)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
two_d_array.shape

(2, 4)

In [7]:
two_d_array.size

8

In [8]:
two_d_array.dtype

dtype('int64')

In [9]:
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.eye( N = 3, 
        M = 5,
        k = 1)


array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [11]:
np.ones(shape=[2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros(shape=[4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Array Indexing and Slicing

In [15]:
one_d_array = np.array([1,2,3,4,5,6])

print(one_d_array)

[1 2 3 4 5 6]


In [14]:
one_d_array[3]

4

In [16]:
one_d_array[3:]

array([4, 5, 6])

In [17]:
one_d_array[::-1]

array([6, 5, 4, 3, 2, 1])

In [19]:
one_d_array + 6

array([ 7,  8,  9, 10, 11, 12])

In [18]:
two_d_array = np.array([one_d_array, one_d_array + 6, one_d_array + 12])
print(two_d_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [20]:
two_d_array[1,4]

11

In [21]:
print(two_d_array)

two_d_array[1:, 4:]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


array([[11, 12],
       [17, 18]])

In [22]:
two_d_array[::-1, ::-1]

array([[18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])

# Reshaping

In [26]:
two_d_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [25]:
np.reshape(a=two_d_array,
           newshape=(6,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [27]:
np.ravel(a=two_d_array,
         order='C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [29]:
print(two_d_array)
np.ravel(a=two_d_array,
         order='F')

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


array([ 1,  7, 13,  2,  8, 14,  3,  9, 15,  4, 10, 16,  5, 11, 17,  6, 12,
       18])

In [30]:
two_d_array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [33]:

N = two_d_array
M = two_d_array.T
print(N)
print(M)
# M[i,j] = N[j,i]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]
 [ 6 12 18]]


In [34]:
print(two_d_array)
np.flipud(two_d_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


array([[13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [35]:
print(two_d_array)
np.fliplr(two_d_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


array([[ 6,  5,  4,  3,  2,  1],
       [12, 11, 10,  9,  8,  7],
       [18, 17, 16, 15, 14, 13]])

In [37]:
print(two_d_array)
np.rot90(two_d_array, k=2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


array([[18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])

In [40]:
# shift elements in an array along given dimensions
print(two_d_array)
np.roll(a=two_d_array,
        shift=2,
        axis=1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


array([[ 5,  6,  1,  2,  3,  4],
       [11, 12,  7,  8,  9, 10],
       [17, 18, 13, 14, 15, 16]])

In [42]:
print(two_d_array)
array_to_join = np.array([[10,20,30], [40,50,60], [70,80,90]])
print(array_to_join)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [43]:
np.concatenate((two_d_array, array_to_join), axis=1)

array([[ 1,  2,  3,  4,  5,  6, 10, 20, 30],
       [ 7,  8,  9, 10, 11, 12, 40, 50, 60],
       [13, 14, 15, 16, 17, 18, 70, 80, 90]])

# Math Operation

$
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
+
e = 
\begin{bmatrix}
a+e & b+e \\
c+e & d+e
\end{bmatrix}
$

In [45]:
print(two_d_array)
two_d_array + 100

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118]])

In [46]:
two_d_array - 100

array([[-99, -98, -97, -96, -95, -94],
       [-93, -92, -91, -90, -89, -88],
       [-87, -86, -85, -84, -83, -82]])

In [47]:
two_d_array * 2

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36]])

In [48]:
two_d_array ** 2

array([[  1,   4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121, 144],
       [169, 196, 225, 256, 289, 324]])

In [49]:
two_d_array % 2

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

In [53]:
small_array = np.array([[1,2], [3,4]])
print(small_array)
small_array + small_array

[[1 2]
 [3 4]]


array([[2, 4],
       [6, 8]])

In [54]:
small_array - small_array

array([[0, 0],
       [0, 0]])

In [55]:
small_array * small_array

array([[ 1,  4],
       [ 9, 16]])

In [56]:
small_array ** small_array

array([[  1,   4],
       [ 27, 256]])

In [58]:
two_d_array
np.mean(two_d_array)

9.5

In [60]:
print(two_d_array)
np.mean(two_d_array, axis=1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


array([ 3.5,  9.5, 15.5])

In [61]:
two_d_array
np.std(two_d_array)

5.188127472091127

In [63]:
print(two_d_array)
np.std(two_d_array, axis=0)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


array([4.89897949, 4.89897949, 4.89897949, 4.89897949, 4.89897949,
       4.89897949])

In [67]:
print(two_d_array)
np.sum(two_d_array, axis=0)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


array([21, 24, 27, 30, 33, 36])

In [68]:
np.log(two_d_array)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947],
       [1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527,
        2.48490665],
       [2.56494936, 2.63905733, 2.7080502 , 2.77258872, 2.83321334,
        2.89037176]])

In [69]:
np.sqrt(two_d_array)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
        3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        , 4.12310563,
        4.24264069]])

# Broadcasting 
![alt text](https://numpy.org/doc/stable/_images/broadcasting_1.png)

"In the simplest example of broadcasting, the scalar b is stretched to become an array of same shape as a so the shapes are compatible for element-by-element multiplication."

In [14]:
A = np.array([1, 2, 3])
print(A)
print("________________")
print(A * 2)

[1 2 3]
________________
[2 4 6]


![alt text](https://numpy.org/doc/stable/_images/broadcasting_2.png "Broadcasting")

A one dimensional array added to a two dimensional array results in broadcasting if number of 1-d array elements matches the number of 2-d array columns.

In [13]:
A = np.array([[0, 0, 0], 
              [10, 10, 10], 
              [20, 20, 20], 
              [30, 30, 30]])
B = np.array([1,2,3])
print(A)
print("________________")
print(B)
print("________________")
print(A + B)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
________________
[1 2 3]
________________
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


![alt text](https://numpy.org/doc/stable/_images/broadcasting_3.png "Broadcasting")

When the trailing dimensions of the arrays are unequal, broadcasting fails because it is impossible to align the values in the rows of the 1st array with the elements of the 2nd arrays for element-by-element addition.



In [12]:
A = np.array([[0, 0, 0], 
              [10, 10, 10], 
              [20, 20, 20], 
              [30, 30, 30]])
B = np.array([1,2,3,4])
print(A)
print("________________")
print(B)
print("________________")
print(A + B)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
________________
[1 2 3 4]
________________


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

![alt text](https://numpy.org/doc/stable/_images/broadcasting_4.png "Broadcasting")


In some cases, broadcasting stretches both arrays to form an output array larger than either of the initial arrays.



In [11]:
A = np.array([[0], 
              [10], 
              [20], 
              [30]])
B = np.array([1,2,3])
print(A)
print("________________")
print(B)
print("________________")
print(A + B)

[[ 0]
 [10]
 [20]
 [30]]
________________
[1 2 3]
________________
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [6]:
import numpy as np 

crime = np.loadtxt('./data/crime.txt', delimiter='\t', dtype=float)
crime

array([[ 478.,  184.,   40.,   74.,   11.,   31.,   20.],
       [ 494.,  213.,   32.,   72.,   11.,   43.,   18.],
       [ 643.,  347.,   57.,   70.,   18.,   16.,   16.],
       [ 341.,  565.,   31.,   71.,   11.,   25.,   19.],
       [ 773.,  327.,   67.,   72.,    9.,   29.,   24.],
       [ 603.,  260.,   25.,   68.,    8.,   32.,   15.],
       [ 484.,  325.,   34.,   68.,   12.,   24.,   14.],
       [ 546.,  102.,   33.,   62.,   13.,   28.,   11.],
       [ 424.,   38.,   36.,   69.,    7.,   25.,   12.],
       [ 548.,  226.,   31.,   66.,    9.,   58.,   15.],
       [ 506.,  137.,   35.,   60.,   13.,   21.,    9.],
       [ 819.,  369.,   30.,   81.,    4.,   77.,   36.],
       [ 541.,  109.,   44.,   66.,    9.,   37.,   12.],
       [ 491.,  809.,   32.,   67.,   11.,   37.,   16.],
       [ 514.,   29.,   30.,   65.,   12.,   35.,   11.],
       [ 371.,  245.,   16.,   64.,   10.,   42.,   14.],
       [ 457.,  118.,   29.,   64.,   12.,   21.,   10.],
       [ 437.,

In [21]:
import pandas as pd
import numpy as np
'''
Crime data for 50 U.S cities.
The data (X1, X2, X3, X4, X5, X6, X7) are for each city.
X1 = total overall reported crime rate per 1 million residents
X2 = reported violent crime rate per 100,000 residents
X3 = annual police funding in $/resident
X4 = % of people 25 years+ with 4 yrs. of high school
X5 = % of 16 to 19 year-olds not in highschool and not highschool graduates.
X6 = % of 18 to 24 year-olds in college
X7 = % of people 25 years+ with at least 4 years of college
'''

df = pd.read_csv('./data/crime.txt', sep='\t', names= ['crime_per_mil',
                                                   'voilent_crime_per_100_000',
                                                   'funding',
                                                   'highschool',
                                                   'no-highschool',
                                                   'college',
                                                   'college4'] )

df

crime_per_mil  voilent_crime_per_100_000  funding  highschool  \
0             478                        184       40          74   
1             494                        213       32          72   
2             643                        347       57          70   
3             341                        565       31          71   
4             773                        327       67          72   
5             603                        260       25          68   
6             484                        325       34          68   
7             546                        102       33          62   
8             424                         38       36          69   
9             548                        226       31          66   
10            506                        137       35          60   
11            819                        369       30          81   
12            541                        109       44          66   
13            491                        809       32          67   
14            514                         29       30          65   
15            371                        245       16          64   
16            457                        118       29          64   
17            437                        148       36          62   
18            570                        387       30          59   
19            432                         98       23          56   
20            619                        608       33          46   
21            357                        218       35          54   
22            623                        254       38          54   
23            547                        697       44          45   
24            792                        827       28          57   
25            799                        693       35          57   
26            439                        448       31          61   
27            867                        942       39          52   
28            912                       1017       27          44   
29            462                        216       36          43   
30            859                        673       38          48   
31            805                        989       46          57   
32            652                        630       29          47   
33            776                        404       32          50   
34            919                        692       39          48   
35            732                       1517       44          49   
36            657                        879       33          72   
37           1419                        631       43          59   
38            989                       1375       22          49   
39            821                       1139       30          54   
40           1740                       3545       86          62   
41            815                        706       30          47   
42            760                        451       32          45   
43            936                        433       43          48   
44            863                        601       20          69   
45            783                       1024       55          42   
46            715                        457       44          49   
47           1504                       1441       37          57   
48           1324                       1022       82          72   
49            940                       1244       66          67   

    no-highschool  college  college4  
0              11       31        20  
1              11       43        18  
2              18       16        16  
3              11       25        19  
4               9       29        24  
5               8       32        15  
6              12       24        14  
7              13       28        11  
8               7       25        12  
9               9       58        15  
10             13       21         9  
11              

In [23]:
y_crime = df['crime_per_mil']
X = df[['funding',
        'highschool',
        'no-highschool',
        'college',
        'college4']]

#numpy ndarrays
A = X.values
b = y_crime.values

# solve for y_crime = X * beta
beta = np.linalg.lstsq(A, b, rcond=None)

beta_formula = np.linalg.inv(A.T@A)@A.T@b
beta[0], beta_formula

(array([11.20228679, -0.16112188, 13.79609146,  3.65440071, -1.45477028]),
 array([11.20228679, -0.16112188, 13.79609146,  3.65440071, -1.45477028]))

In [24]:
['funding', 'highschool', 'no-highschool', 'college', 'college4']

['funding', 'highschool', 'no-highschool', 'college', 'college4']

In [1]:
# "editor.parameterHints.enabled": false